"""Driver protocol stub."""
from __future__ import annotations
from typing import Protocol
from core.types import Joints, MoveHandle, Pose, Result


class IRobotDriver(Protocol):
    async def read_joints(self) -> Result[Joints]: ...
    async def command_joint_goal(self, joints: Joints, speed: float, accel: float) -> Result[MoveHandle]: ...
    async def command_cartesian_goal(self, pose: Pose, speed: float, accel: float, frame: str = "base") -> Result[MoveHandle]: ...
    async def stop(self) -> Result[None]: ...


class IServo(Protocol):
    def set_angle(self, angle: int) -> bool: ...
    def close(self): ...
